server:
 port: 9000

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/newtsleehdb
  username: root
  password: SteveAmazon_1998
 jpa:
  hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  show-sql: true
  